/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2026-02-27 22:36:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1769081796000L));
    _jspx_dependants.put("jar:file:/C:/Users/Lenovo%20E14/Desktop/Online_Voting_System/voting-system/apache-tomcat-10.1.28/webapps/online-voting-system/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664449878000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/fragment/head.jsp", out, false);
      out.write("\n");
      out.write("    <title>Online Voting System | Home</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/fragment/navbar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <main class=\"container py-4 py-md-5\">\n");
      out.write("        <section class=\"hero-wrap mb-5\">\n");
      out.write("            <div class=\"overlay-content text-center text-md-start\">\n");
      out.write("                <p class=\"section-label mb-2\">Civic Tech Demo</p>\n");
      out.write("                <h1 class=\"display-3 mb-3\">Vote Smarter. Lead Better.</h1>\n");
      out.write("                <p class=\"lead mb-4\">A secure, session-based election platform built with Jakarta EE, JSP, JPA, and MySQL.</p>\n");
      out.write("                <div class=\"d-flex flex-wrap gap-2 justify-content-center justify-content-md-start\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register-view\" class=\"btn btn-light btn-lg px-4\">Create Account</a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login-view\" class=\"btn btn-outline-light btn-lg px-4\">Access Dashboard</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"row g-3 mb-5\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"soft-panel h-100\">\n");
      out.write("                    <p class=\"section-label mb-1\">Security</p>\n");
      out.write("                    <div class=\"metric\">BCrypt + JPA</div>\n");
      out.write("                    <p class=\"text-muted mb-0\">Password hashing, role-based access, and protected authenticated routes.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"soft-panel h-100\">\n");
      out.write("                    <p class=\"section-label mb-1\">Fairness</p>\n");
      out.write("                    <div class=\"metric\">One Voter, One Vote</div>\n");
      out.write("                    <p class=\"text-muted mb-0\">Database-level one-vote rule and admin-controlled contester approvals.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"soft-panel h-100\">\n");
      out.write("                    <p class=\"section-label mb-1\">Transparency</p>\n");
      out.write("                    <div class=\"metric\">Live Count View</div>\n");
      out.write("                    <p class=\"text-muted mb-0\">Vote totals are visible in read-only mode for all approved contesters.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"card\">\n");
      out.write("            <div class=\"card-body p-4 p-md-5\">\n");
      out.write("                <h2 class=\"mb-3\">What This Demo Includes</h2>\n");
      out.write("                <div class=\"row g-3 text-muted\">\n");
      out.write("                    <div class=\"col-md-6\"><i class=\"bi bi-check2-circle text-success me-2\"></i>User registration with email verification</div>\n");
      out.write("                    <div class=\"col-md-6\"><i class=\"bi bi-check2-circle text-success me-2\"></i>Session-based login for voters/admins</div>\n");
      out.write("                    <div class=\"col-md-6\"><i class=\"bi bi-check2-circle text-success me-2\"></i>Contester applications and admin approval</div>\n");
      out.write("                    <div class=\"col-md-6\"><i class=\"bi bi-check2-circle text-success me-2\"></i>Position cap rule (max 3 approved)</div>\n");
      out.write("                    <div class=\"col-md-6\"><i class=\"bi bi-check2-circle text-success me-2\"></i>Dashboard voting and statistics</div>\n");
      out.write("                    <div class=\"col-md-6\"><i class=\"bi bi-check2-circle text-success me-2\"></i>Profile update and password management</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/fragment/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
